### PR TITLE
bug: fix mistached param name in sessions api

### PR DESCRIPTION
**Pull request by taciturnaxolotl**

### CODE REVIEW

**Comment by taciturnaxolotl** [comment]
@techpixel i updated the branch and this should fix the api issues

**Comment by taciturnaxolotl** [comment]
image
image
rn pullin my slackid from the api gets a random session it seems

**Comment by taciturnaxolotl** [comment]
their slackId is: `U07D78V01KP`

**Comment by techpixel** [comment]
Closing this as it has been already resolved

**Pull request closed without merging**
