### PR TITLE
feat: make the session api open and not requiring authentication

### PR DESCRIPTION
**Pull request by taciturnaxolotl**
This is really helpful for users trying to make arcade tools like mine, which need to be able to determine the thread ts of the user's active session

### CODE REVIEW

**Comment by taciturnaxolotl** [comment]
I added a check for whether the token is valid, so It's not completely open

**Review by rutmanz — APPROVED** [review]

**Comment by taciturnaxolotl** [comment]
Ooooohhh!!! I’d this gets merged that would be super helpful for grolf v2!

**Comment by taciturnaxolotl** [comment]
@maxwofford could this please get merged? It would be super helpful for grolf

**Comment by taciturnaxolotl** [comment]
@rutmanz can you merge this? idk if you have merge permissions but that would be super helpful for grolf

**Comment by rutmanz** [comment]
Sorry, I'm not part of HC HQ, and I'm not a maintainer of this repository. You'll have to wait for @techpixel to review and merge

**Comment by taciturnaxolotl** [comment]
ah, okay thanks!

**Comment by techpixel** [comment]
sorry kieran! everything lgtm, I'll merge it

**Comment by taciturnaxolotl** [comment]
yay!!!! thanks!!!!

**Pull request merged**
